#ifndef APP_AUDIO_SERVICE_H_
#define APP_AUDIO_SERVICE_H_

#include <stdint.h>

typedef enum {
	APP_AUDIO_EVENT_TEST = 0,
	APP_AUDIO_EVENT_WELCOME,
	APP_AUDIO_EVENT_ENV_LIGHT_LOW,
	APP_AUDIO_EVENT_ENV_LIGHT_HIGH,
	APP_AUDIO_EVENT_ENV_TEMP_LOW,
	APP_AUDIO_EVENT_ENV_TEMP_HIGH,
	APP_AUDIO_EVENT_ENV_HUMI_LOW,
	APP_AUDIO_EVENT_ENV_HUMI_HIGH,
	APP_AUDIO_EVENT_CONFIRM,
	APP_AUDIO_EVENT_TODO_SYNC_UP,
	APP_AUDIO_EVENT_REST_REMINDER,
	APP_AUDIO_EVENT_ALARM,
	APP_AUDIO_EVENT_HOUR_CHIME,
	APP_AUDIO_EVENT_WIFI_CONNECTED,
} app_audio_event_t;

#endif
